version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "16379:6379"

  log-server:
    build:
      context: .
      dockerfile: Dockerfile.log_server
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "53423:53423"
    depends_on:
      - redis
    volumes:
      - ./logview_data:/app/logview_data
      - ./internal/templates:/app/internal/templates
      - ./internal/static:/app/internal/static

  log-worker:
    build:
      context: .
      dockerfile: Dockerfile.log_worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ./logview_data:/app/logview_data
